name: Deploy Frontend

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Update Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Notelify
            git pull origin dev

            cat > .env <<EOF
            VITE_API_URL=https://catchathought.ddns.net/api
            VITE_WS_URL=https://catchathought.ddns.net
            EOF

            npm install
            npm run build

            sudo rm -rf /var/www/catchathought/frontend/*
            sudo cp -r dist/* /var/www/catchathought/frontend/

            sudo chown -R www-data:www-data /var/www/catchathought/frontend
            sudo chmod -R 755 /var/www/catchathought/frontend

            sudo systemctl reload nginx